version: '2'
services:
  web:
    build:
      context: ./nginx
    ports: 
     - "8081:80"
     - "443:443"    
  spring1:
    build:
      context: ./spring
      args:
        JAR_FILE: target/gs-spring-boot-docker-0.1.0.jar  
    volumes:
    - ./file:/home/file
  spring2:
    build:
      context: ./spring
      args:
        JAR_FILE: target/gs-spring-boot-docker-0.1.0.jar      
    volumes:
    - ./file:/home/file
      
 
